---
configure_bashit: yes
configure_dotfiles: yes
configure_gvm: yes
configure_osx: yes

dotfiles_repo: https://github.com/dcode/dotfiles.git
dotfiles_repo_local_destination: ~/Projects/dotfiles
dotfiles_files:
  - .bash_profile
  - .bashrc
  - .dircolors
  - .gitconfig
  - .gitignore
  - .inputrc
  - .osx
  - .tmux.conf
  - .vimrc

# Bash-It vars
theme: cooperkid

homebrew_installed_packages:
  - ansible-lint
  - awscli
  - bash-completion
  - bitwarden-cli
  - blueutil
  - bzip2
  - coreutils
  - gettext
  - git
  - go
  - gpg2
  - hping
  - httpie
  - jq
  - kafkacat
  - kubernetes-cli
  - libyaml
  - nmap
  - openssl
  - pianobar
  - pyenv
  - pyenv-virtualenv
  - readline
  - shellcheck
  - sqlite
  - ssh-copy-id
  - terraform
  - vault
  - yamllint

homebrew_taps:
  - homebrew/cask
  - homebrew/cask-drivers
  - homebrew/core

homebrew_cask_apps:
  - bitwarden
  - chromedriver
  - dotnet-sdk
  - firefox
  - google-chrome
  - google-cloud-sdk
  - iterm2
  - keybase
  - logitech-options
  - mactex-no-gui
#   - notion
  - slack
  - usb-overdrive
  - vagrant
#   - virtualbox
#   - virtualbox-extension-pack
  - visual-studio-code
  - vlc
  - vmware-remote-console
  - whatsapp
  - wireshark
  - zoomus

mas_installed_apps:
  - { id: 937984704, name: "Amphetamine" }
  - { id: 1295203466, name: "Microsoft Remote Desktop" }
#   - { id: 1439967473, name: "Okta Browser Extension" }
  - { id: 1451685025, name: "WireGuard" }
  - { id: 414030210, name: "Limechat" }
  - { id: 441258766, name: "Magnet" }
  - { id: 585829637, name: "Todoist" }
#   - { id: 856124300, name: "inShort" }
  - { id: 920404675, name: "Monodraw" }
  - { id: 975937182, name: "Fantastical" }
  - { id: 425424353, name: "The Unarchiver" }
  - { id: 1381004916, name: "Discovery" }
  - { id: 1193539993, name: "Brother iPrint&Scan" }
